### PR TITLE
scrollbar ui update #101

### LINKED ISSUE #101: [Feature] Enhance Scrollbar of Website
### Description

- The Scrollbar of website looks preety much blunt, doesn't matches with Website Ui.
- We can enhance the Scrollbar to match with overall UI.

# Current Scrollbar Snapshot
image

# what we can achieve
image

### Additional Information

- update : Already working on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anujsingh4545**
# What does this PR do
- This PR improves the Scrollbar of website.
- Matches Ui of srollbar to overall website.

Fixes #101 

## How Should this be tested.
- Open Website.
- Scroll down.
- Look at the updated scrollbar.

## Changed Snapshot

https://github.com/AbhiPatel10/openzone/assets/76861751/fba016bf-80f2-485d-bad1-ec6674bbb7e0

## Info to maintainers
- Merge it if you like it.
- P.s  : I don't belong to Gssoc community.

### CODE REVIEW

**Review by AbhiPatel10 — APPROVED** [review]

**Comment by AbhiPatel10** [comment]
Please resolve this conflicts

**Comment by anujsingh4545** [comment]
@AbhiPatel10 resolved the conflicts, here also !

**Comment by AbhiPatel10** [comment]
Please check once This PR

**Comment by anujsingh4545** [comment]
@AbhiPatel10 again resolved the conflicts !

**Pull request merged**
