### PR TITLE
fixes search error #99

### LINKED ISSUE #99: [Bug] Search Request not triggering while clicking Enter
### What would you like to share or ask?

# Description
- In projects Search Page, while searching something, the general behaviour should be, if user click enter or seach button in both cases search should trigger.
- But in this case clicking on search only triggering, search.
- This submit type is inefficent.

image

### Additional information

- Update : Already working into this issue.
- Note : I'm not gssoc contributor, so tags are not needed.

### PR DESCRIPTION
**Pull request by anujsingh4545**
## What does this PR do
- This PR improves the search panel.
- Even by clicking enter you can submit your search.
- Increases Overall Performace.

Fixes #99 

## How Should this be tested.
- Go to projects.
- Search something.
- Click on enter.

## Changed Snapshot

https://github.com/AbhiPatel10/openzone/assets/76861751/d6646e28-20f5-40ea-a8ff-6c4c4d9d73eb

### CODE REVIEW

**Review by AbhiPatel10 — APPROVED** [review]
Looks good to me Thanks for your contribution @anujsingh4545

**Comment by AbhiPatel10** [comment]
There some Conflicts, Please resolve it.

**Comment by anujsingh4545** [comment]
@AbhiPatel10 sry, i was busy around something, resolved merged conflicts now, please check it !

**Comment by AbhiPatel10** [comment]
All good, Thanks for your contribution @anujsingh4545

**Pull request merged**
