### PR TITLE
Solved #55, Improved project search UI

### LINKED ISSUE #55: Search UI can be improved
### What would you like to share or ask?

Screenshot 2024-05-14 231307

The Footer of search page is overlapping with search results. I would like to work on this issue and improve it. Please assign me this issue under GSSOC 2024

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AgrikMaz**
Closes #55 

## Fixes Issue

1. Search result cards spacing with footer has been improved
2. URL links have been stopped from overflowing off the result cards
3. Converted text URL to working links

## Screenshots
Changed
Screenshot 2024-05-16 091839
To
Screenshot 2024-05-16 090943

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Please improve, this UI Properly.

**Comment by AgrikMaz** [comment]
Done, pls recheck

**Comment by AdhithiManjunath** [comment]
please assign me this issue so that i can work on it .

**Comment by AbhiPatel10** [comment]
Not expecting a new Package Just for loader....

**Pull request closed without merging**
